# Generated by Django 2.2.5 on 2022-03-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staffId', models.IntegerField()),
                ('sectorId', models.IntegerField()),
                ('tempture', models.FloatField()),
                ('checkTempture', models.FloatField(null=True)),
                ('operator', models.CharField(max_length=50, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('specification', models.CharField(max_length=20, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('operator', models.CharField(max_length=50)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.BigIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('sex', models.BooleanField()),
                ('age', models.SmallIntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('sector', models.IntegerField()),
                ('position', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
