# Generated by Django 2.2.5 on 2022-03-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goodId', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('goodName', models.CharField(max_length=50)),
                ('sectorId', models.IntegerField()),
                ('sectorName', models.CharField(max_length=50)),
                ('applyTime', models.DateTimeField(auto_now_add=True)),
                ('approveTime', models.DateTimeField()),
                ('status', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'applicationview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goodId', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('sectorId', models.IntegerField()),
                ('applyTime', models.DateTimeField(auto_now_add=True)),
                ('approveTime', models.DateTimeField()),
                ('status', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
