# Generated by Django 2.2.5 on 2022-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_application_applicationview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=30)),
                ('uid', models.BigIntegerField()),
                ('tempture', models.FloatField()),
                ('checkTempture', models.FloatField(null=True)),
                ('operator', models.CharField(max_length=50, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'attendanceview',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='approveTime',
            field=models.DateTimeField(null=True),
        ),
    ]
