# Generated by Django 2.2.5 on 2022-03-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220322_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='sectorId',
        ),
    ]
