# Generated by Django 2.2.5 on 2022-03-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_attendance_sectorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodApply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goodId', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('staffId', models.IntegerField()),
                ('isPass', models.BooleanField()),
                ('isRead', models.BooleanField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutsideInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staffId', models.IntegerField()),
                ('sectorId', models.IntegerField()),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=10)),
                ('applyDate', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('approveStatus', models.SmallIntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
