# Generated by Django 2.2.5 on 2022-03-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_goodapply_outsideinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideInfoView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staffId', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('sectorId', models.IntegerField()),
                ('sectorName', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=10)),
                ('applyDate', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('approveStatus', models.SmallIntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'outsideinfoview',
                'managed': False,
            },
        ),
    ]
