# Generated by Django 2.2.5 on 2022-03-29 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_outsideinfoview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outsideinfo',
            old_name='date',
            new_name='endDate',
        ),
        migrations.AddField(
            model_name='outsideinfo',
            name='startDate',
            field=models.DateTimeField(default=datetime.date(2022, 3, 29)),
        ),
    ]
