# Generated by Django 2.2.5 on 2022-03-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220329_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideinfo',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
