# Generated by Django 2.2.5 on 2022-03-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220329_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outsideinfo',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='outsideinfo',
            name='startDate',
        ),
    ]
