# Generated by Django 2.2.5 on 2022-03-29 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220329_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideinfo',
            name='endDate',
            field=models.DateField(default=datetime.date(2022, 3, 29)),
        ),
        migrations.AddField(
            model_name='outsideinfo',
            name='startDate',
            field=models.DateField(default=datetime.date(2022, 3, 29)),
        ),
    ]
