# Generated by Django 2.2.5 on 2022-03-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220329_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideinfo',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='outsideinfo',
            name='startDate',
            field=models.DateField(),
        ),
    ]
