# Generated by Django 2.2.5 on 2022-03-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_staffview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outsideinfo',
            name='sectorId',
        ),
        migrations.AlterField(
            model_name='sector',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
